

namespace NewAsset.Application.Common.Utilities
{
    public class AppSettings
    {
        public string Appkey { set; get; }
        public string Tier1Depositmax { set; get; }
        public string AssetMailSubjectHeader { set; get; }
        public string Tier1CummulativeMax { set; get; }
        public string Tier2Depositmax { set; get; }
        public string Tier2CummulativeMax { set; get; }
        public string PlayStoreUser { set; get; }
        public string PlayStoreUserOtp { set; get; }
        public string SuggestedBankUrl { set; get; }
        public string SupportPhoneNumber { set; get; }
        public string SupportEmail { set; get; }
        public string SupportWebsite { set; get; }
        public string UpSystemMaintenance { set; get; }
        public string SmsAlertNotification { set; get; }
        public string EmailAlertNotification { set; get; }
        public string DownSystemMaintenance { set; get; }
        public string Tier3Depositmax { set; get; }
        public string Tier3CummulativeMax { set; get; }
        public string Urlfilepath { set; get; }
        public string RedisIPAndPassword { set; get; }
        public string RedisInstanceName { set; get; }
        public string ldapServer { set; get; }
        public int ldapPort { set; get; }
        public string ldapBaseDn { set; get; }
        public string InterestOnFixedDepositInvestment { get; set; }
        public string RetailLoanInterestRate { get; set; }
        public string HalalFixedDepositproductcode { set; get; }
        public string publicLoanEvaluation { set; get; }
        public string FixedDepositproductcode { set; get; }
        public string newbvnurl { get; set; }
        public string authloginusername { set; get; }
        public string authpassword { set; get; }
        public string AssetMailSubject { set; get; }
        public string secondevaluation { set; get; }
        public string sessionusername { set; get; }
        public string sessionpassword { set; get; }
        public string LoanSessionUsername { set; get; }
        public string LoanSessionPassword { set; get; }
        public string LoanSessionUrl { set; get; }
        public string SubmitLoanEvaluation { set; get; }
        public string SessionUrl { set; get; }
        public string firstevaluation { set; get; }
        public string LoanRequestTypes { set; get; }
        public string LoanTypes { get; set; }
        public string CustNinUrlFromUssd { set; get; }
        public string NinLoginUrlFromUssd { get; set; }
        public string NinLoginusernameFromUssd { get; set; }
        public string NinLoginPwdFromUssd { get; set; }
        public string BillsRecordGetterUrl { get; set; }
        public string SamplePhoneNumber { set; get; }
        public string TransferChargesGL { set; get; }
        public string VatChargesGL { set; get; }
        public string GetCustomerData { set; get; }
        public string InterestOnHalaInvestment { set; get; }
        public string AccessCheckSumKey { get; set; }
        public string HilalInvestmentGL { set; get; }
        public string CustomerServiceEmail { set; get; }
        public string OperationEmail { set; get; }
        public string NintokenEndpointUrl { get; set; }
        public string SmsUrl { set; get; }
        public string NipCharges { set; get; }
        public string InterestOnPrimeLockFixedDeposits { get; set; }
        public string MoneyMarketDestinationBankCode { get; set; }
        public string MoneyMarketDestinationAccountNo { get; set; }
        public string MoneyMarketDestinationAccountName { get; set; }
        public string PicFileUploadPath { set; get; }
        public string BillspaymentGL { get; set; }
        public string vas2nets { get; set; }
        public string FixedDepositGL { get; set; }
        public string MutualFundPin { get; set; }
        public string MoneyMarketGL { get; set; }
        public string ContextPath { set; get; }
        public string FireBase { set; get; }
        public string NinUserNameEndPoint { get; set; }
        public string NinPasswordEndPoint { get; set; }
        public string IntegratorUrl { get; set; }
        public string InterBankKey { get; set; }
        public string NinEndPoint { get; set; }
        public string LogPath { get; set; }
        public long CookieLengthDays { get; set; }
        public string FilePath { get; set; }
        public string SendSms { get; set; }
        public string SendEmail { get; set; }
        public string TransactionType { get; set; }
        public string RestrictedAccountTypes { get; set; }
        public string UseAd { get; set; }
        public string UserManagementUrl { get; set; }
        public string FinedgeUrl { get; set; }
        public string billpayment { get; set; }
        public string FinedgeKey { get; set; }
        public string BvnUrl { get; set; }
        public string BvnKey { get; set; }
        public string ProductCode { get; set; }
        public string AccessUrl { get; set; }
        public string AccessKey { get; set; }
        public string AccessLiveNameEnquiry { get; set; }
        public string AirtimeUrl { get; set; }
        public string AirtimeKey { get; set; }
        public string ZanibalUrl { get; set; }
        public string WorkflowUrl { get; set; }
        public int PasswordExpiry { get; set; }
        public int SessionLenght { get; set; }
        public string ValidateSession { get; set; }
        public int RegMaxTime { get; set; }
        public string DemoOtp { get; set; }
        public int SavingAccountProduct { get; set; }
        public string TrustBancBankCode { get; set; }
        public string TrustBancBankName { get; set; }
        public int Retries { get; set; }
        public int TopBeneficiaryCount { get; set; }
        public decimal Vat { get; set; }
        public string Production { get; set; }
        public string RetriveUsernameText { get; set; }
        public string FileLocation { get; set; }
        public string FileUploadPath { get; set; }
        public string CheckDevice { get; set; }
        public decimal LoanManagementFee { get; set; }
        public decimal WithholdingTax { get; set; }
        public string IndemnityformPath { get; set; }
        public string TransTimeInterval { get; set; }
        public string BranchCode { get; set; }
        public string AccountUrl { get; set; }
        public string PartialViews { get; set; }
    }
}
